### ISSUE TITLE
Would someone be able to build me a PowerPC version of the client?

### ISSUE THREAD

**Issue by Krutonium** [nextcloud/client_theming#129]
I want to use the client on my PowerPC Mac, running OS X 10.5.8, the last available version of OS X for PowerPC. I would build it myself, but that is also my newest Mac, and it only has a 60GB HDD/725MB of Ram.

Thanks!

**Comment by shaman007** [comment]
Hello,

Are you aware of security problems that that much outdated system has?
Most likely this system would not be able to build the client due to it
does not have proper TLS libs. Seriously, the Raspbery Pi is more
powerful and you will spend it cost just as electricity bills.

-----Original Message-----

Date: Wed, 26 Apr 2017 05:36:37 -0700
Subject: [nextcloud/client_theming] Would someone be able to build me a
PowerPC version of the client? (#129)
Cc: Subscribed <subscribed@noreply.github.com>
To: nextcloud/client_theming <client_theming@noreply.github.com>
Reply-to: nextcloud/client_theming <reply+006903a02d63c624bd30317685401
eada78fee522d39c7ff92cf000000011518565592a169ce0d60e0c4@reply.github.co
m>
From: Krutonium <notifications@github.com>
I want to use the client on my PowerPC Mac, running OS X 10.5.6, the
last available version of OS X for PowerPC. I would build it myself,
but that is also my newest Mac, and it only has a 60GB HDD/725MB of
Ram.

Thanks!


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



  
  





{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c554
93e4bb","name":"GitHub"},"entity":{"external_key":"github/nextcloud/cli
ent_theming","title":"nextcloud/client_theming","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/asset
s/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.c
om/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/nextcloud/client_theming"}},"updates"
:{"snippets":[{"icon":"DESCRIPTION","message":"Would someone be able to
build me a PowerPC version of the client?
(#129)"}],"action":{"name":"View
Issue","url":"https://github.com/nextcloud/client_theming/issues/129"}}
}
-- 
With best regards,
Andrey Bondarenko
mail:me@andreybondarenko.com
https://andreybondarenko.com
skype:andrey.bondarenko

**Comment by Krutonium** [comment]
Yes yes, I know, but this is part of a personal project I am doing - in fact, this computer is actually dualbooted with Ubuntu Mate 16.04. I want to see if this computer can be made "Usable". Though TBH, I don't think I am going to run into any huge security issues, owing to the PowerPC Processor - no modern malware is capable of running on it, and it's such an old target, I can't see anyone really targeting it. Plus it's behind a firewall.

**Comment by enoch85** [comment]
Please ask this question in the forums instead. Thank you!

https://help.nextcloud.com/c/nextcloud-freelancing/looking
