### ISSUE TITLE
Can't start the client

### ISSUE THREAD

**Issue by volker-raschek** [nextcloud/client_theming#148]
Hello, 
I can't start the nextcloud-client on my Linux Mint 18.1 OS. I can't see a window, if I start it from the console I get this error message.

```
markus@markus-nb ~ $ nextcloud
nextcloud: symbol lookup error: /usr/lib/x86_64-linux-gnu/libnextcloudsync.so.0: undefined symbol: _ZN9QKeychain15ReadPasswordJob6setKeyERK7QString
```

How I can fix it or must do to fix it?
Volker

**Comment by ivaradi** [comment]
Hello,

assuming that you use the Xenial (Ubuntu 16.04) version from the PPA, the problem could be a wrong version of the libqt5keychain0 package. The PPA package is built with version 0.5.0-1build1~gcc5.1, which is the standard version on Xenial. Perhaps you have a different version. If so, try to install this or a similar version (I would say the 0.5 part is the most important).

**Comment by volker-raschek** [comment]
Ohh tanks, it's the solution.
I have a new version from this package.
```
markus@markus-nb ~ $ dpkg --list | grep libqt5keychain
ii  libqt5keychain0                              0.6.2-1.1                                  amd64        Cross platform password store library
ii  libqt5keychain1                              0.7.0-9.5                                  amd64        Cross platform password store library
```

I've installed the older version from the ubuntu [repo](http://packages.ubuntu.com/yakkety/amd64/libqt5keychain0/download) and can start the client application now! Thanks!

```
markus@markus-nb ~ $ dpkg --list | grep libqt5keychain
ii  libqt5keychain0:amd64                        0.5.0-1build1~gcc5.1                       amd64        Qt API to store passwords (QT5 version)
ii  libqt5keychain1                              0.7.0-9.5                                  amd64        Cross platform password store library
```

**Comment by smiddy** [comment]
Solved the problem for me as well! Same problem on same OS. But I have no idea where the more recent version was installed from...

**Comment by enoch85** [comment]
This seems to be fixed. Please remember to always close fixed issues. Thank you!

**Comment by LeCoyote** [comment]
FYI, the problem is still present in the 2.3.2 package from the PPA. Building from source works though.

**Comment by ivaradi** [comment]
This problem is actually not a problem with the client package, because it is built with the "official" version of the libqt5keychain0 package. If we built it with the newer version, people using Xenial with the packages that come with it would no be able to use the client package. (The correct way to avoid this problem would have been to make the 0.6.x version to be package libqt5keychain1 (note the "1" at the end), and the 0.7.x version to be libqt5keychain2, but it is beyond our control.)

**Comment by LeCoyote** [comment]
Ok, so what is it a problem with? All I know is that I'm using stock Mint 18.1 packages, the xenial packages from the Nextcloud PPA, and that when I updated to 2.3.2 the desktop client stopped working. I'm not pointing fingers, just reporting that the issue is still current :)

**Comment by ivaradi** [comment]
The problem is that Mint contains the newer (0.6) version of the `libqt5keychain0` package, whereas Xenial contains the 0.5 version. So this is a slight incompatibility between Mint and Xenial. 

So if you want to use the client on Mint, you need to install the 0.5 version of `libqt5keychain0` from the Ubuntu repo as described by @volker-raschek above.

I was trying to find something that supports PPAs (or similar repositories) for Mint, but could not. If you know of something, I would be happy to investigate it and perhaps provide packages built specifically for Mint.

**Comment by LeCoyote** [comment]
Well I'm running Mint 18.1 at the moment, so `libqt5keychain0` is 0.5.x, but the problem still exists.

**Comment by ivaradi** [comment]
Then it is probably a different problem. Do you get the same error messages, as in the original posting?
