### ISSUE TITLE
TLS versions 1.1 & 1.2 only not supported

### ISSUE THREAD

**Issue by ZiiX** [nextcloud/client_theming#22]
I tried to force `SSLProtocol -ALL +TLSv1.1 +TLSv1.2` but the desktop client Mac refuses to connect.

Once I added back **+TLSv1** it started to work again. 
`SSLProtocol -ALL +TLSv1 +TLSv1.1 +TLSv1.2`

Furthermore, the dropdown menu from the green lock shows SSLv3 though I do not have that option available and SSLabs confirms this isn't allowed.

I'm running fresh install NC10 + apache per instructions favored.

---

_Thank you for all the amazing work y'all. Loving my NextCloud._

**Comment by serge-vk** [comment]
This seems to be the same issue (#13) that I reported a week ago. I use nginx, though.

**Comment by Darkspirit** [comment]
2 more macOS users affected. TLSv1.2 only, ECDHE-ECDSA-AES256-GCM-SHA384 only, (ECDSA curve secp384r1 + ECDHE curves secp521r1:secp384r1). But the Owncloud 3.2.2 desktop client works! Might be that you don't ship the right OpenSSL with your Nextcloud Qt build.

**Comment by piwats** [comment]
Any news?

**Comment by rullzer** [comment]
Yes duplicate of #13

**Comment by zeigerpuppy** [comment]
I managed to solve this with an update to cyphers on apache2.4.  It now works with nextcloud client on OS X and passes A+ with https://www.ssllabs.com/ssltest

Here's the cypher setup that works (I haven't enabled stapling):

```apache
SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
SSLProtocol All -SSLv2 -SSLv3
SSLHonorCipherOrder On
Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
Header always set X-Frame-Options DENY
Header always set X-Content-Type-Options nosniff
# Requires Apache >= 2.4
SSLCompression off
#SSLUseStapling on
#SSLStaplingCache "shmcb:logs/stapling-cache(150000)"
# Requires Apache >= 2.4.11
SSLSessionTickets Off
```

**Comment by Darkspirit** [comment]
@zeigerpuppy No, you are wrong.
The current nextcloud macOS client uses a very outdated OpenSSL version and can only use up to TLS 1.0.
You wouldn't be able to do anything, if you would have "SSLProtocol All -TLSv1.1 -TLSv1 -SSLv3 -SSLv2". But you should have TLSv1.2-only.
Your "solution" here is to use TLS 1.0. That is no solution.^^

**Comment by zeigerpuppy** [comment]
that's weird because it works well for me, nextcloud gives no error and the suite passes A+ with SSLLabs

**Comment by Darkspirit** [comment]
You don't realize, that "A+" doesn't mean TLS 1.2-only. Your server simply support "secure https" (TLS 1.2) and "legacy https with security problems" (TLS 1.0). The macOS nextcloud client would then connect via the "legacy TLS 1.0 with security problems" and you are thinking everything might be just fine because it works?

**Comment by zeigerpuppy** [comment]
The SSLLabs test includes tests for insecure cyphers (that's the whole point of testing!).  Have you tried the cypher suite suggested?

**Comment by Darkspirit** [comment]
@zeigerpuppy You do not know what you are talking about. It's not about cipher suites.

**Comment by zeigerpuppy** [comment]
Well it does seem like you're getting excited.  My understanding is this:  the web server presents certain options (protocols and cyphers) which are offered for negotiation to the client.  It seems that in the case of this error, the nextcloud client is choosing a protocol which is not permitted for negotiation.  Now this may be to do with outdated TLS version and I agree that this is a potential security hole.
Nevertheless, I would say that the (Apache 2.4, Debian) settings I have presented work with the later nextcloud client on OS X (Mavericks) and also do not seem to compromise SSL security (as far as SSLLabs is concerned).
I'd suggest rather than focusing your efforts on ad-hominem comments that we keep the thread to strictly technical matters.
Happy to hear your thoughts (and tests) as to why the proposed workaround is flawed.

**Comment by Darkspirit** [comment]
Old protocols are only acceptable for not longer maintained software. You can't suggest to use outdated security standards if you can use modern encryption. The nextcloud macOS client is only a fork with another name. The only solution is to tell people why Nextcloud is better (like LibreOffice is better than OpenOffice) in the long term and suggest to use the owncloud macOS client at least until the build process is fixed.

**Comment by jospoortvliet** [comment]
Stay friendly, friends ;-)

I am clueless on TLS/SSL and such but I do know that "You do not know what you are talking about" is disrespectful.

**Comment by zeigerpuppy** [comment]
I'm not sure why @TerraX-net is getting so excited.  The settings I mentioned in #22 pass all known TLS/SSL vulnerability tests.  They are settings generated from https://cipherli.st/ and pass every test I have been able to throw at them (iuncluding http://ssl-checker.online-domain-tools.com/ and https://www.ssllabs.com/ssltest/).  

I would love @TerraX-net to try testing them and let me know which particular test is failed.  The settings do prevent downgrade attacks and only support the TLS1.0 suites not affected by vulnerabilities, for example, see these reported TLS1.0 cyphers:

```
LS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)	Secure	256	Yes	No	No	Yes
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39) DH 4096 bits	Secure	256	Yes	No	No	No
```

At this stage I would have to say that @TerraX-net is just spreading FUD.
But don't trust me, test it yourself.  While some implementations of TLS 1.0 are definitely insure, not all are.  I have upgraded libssl to the latest too.  What we are seeing here is a case where given the right options, there is a TLS negotiation that can be made secure with the current nexcloud client.  I certainly agree that nextcloud should be updated for TLS1.2 but that doesn't mean the solution presented is insecure.

I look forward to the client being updated but in the meantime, when users log in to nextcloud they are directed to install the nextcloud client.  I can't necessarily control that behaviour so I have made it as secure as possible server-side.  I am happy to provide more details but may just ignore @TerraX-net from now on considering how agitated they seem to be.

**Comment by Darkspirit** [comment]
@zeigerpuppy That's the problem of the authors of such tests: The tests are designed to prevent users doing something much worse and try to motivate them to do better. CBC-SHA1 ciphers are not AEAD ciphers with SHA2. That's sufficient for you. We all have to prevent the use of old encryption in recent setups.

**Comment by areilly** [comment]
@zeigerpuppy https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.1 says that TLSv1.1 was specified in 2006 (ten years ago), in response to some noted flaws in 1.0.  It was first supported in openssl in 2012, according to the change log.  There are *lots* of how-to-set-up-ssl discussions that advise to drop everything before TLSv1.1.  The trick to secure encryption is to accept the advice of experts (I am not one.)  What possible justification could there be for a *new* network application to *not* support TLSv1.1 and 1.2?  It makes no sense.

I've converted my owncloud to nextcloud today, in the hope of a more vibrant development environment (seems to be the case) and well supported two-factor authentication.  This thread and the one I came in on (when my newly installed nextcloud macOS client wouldn't connect to my otherwise functioning FreeBSD11+apache24 nextcloud instance) is not giving me as much comfort as I had hoped.

**Comment by zeigerpuppy** [comment]
I totally agree with you that the client needs to be fixed.
All I have suggested is a workaround that allows the use of the current nextcloud client in the least worse configuration!
As a user you're probably best using the owncloud client.  But this was confusing for users in my case so I posted this workaround.
I totally agree that we should be using TLS 1.2, although the config that I have specified is resistant to known attacks on TLS 1.0.

**Comment by Derridaralalala** [comment]
@zeigerpuppy @TerraX-net TLS 1.0 (insecure) is indeed outdated and hardening your server would indeed may mean to allow i.e. TLS1.2 only (cf. http://tinyurl.com/n6zggvy). Having said that; in some deployment scenarios it is still reasonable to use TLS 1.0 or TLS 1.1 for i.e. the sake of compatibility or company policy. Also, some "authorities" such as PCI DSS or HIPAA (Health Information Privacy) do request or recommend such a compatibility, at least with TLS 1.1.

@rullzer I hope this issue will be solved with the next productive desktop client. Having up to date OpenSSL builts implemented in clients is desirable from a security and system health perspective.

**Comment by jeffreyvangorkum** [comment]
Apparently the 2.3.0.4RC1 works with TLS1.2.

**Comment by gcosta74** [comment]
It is time to solve this ! Any updates ?

**Comment by bbgrk** [comment]
+1 We need this.

**Comment by jcw** [comment]
Same prob here - I'm using the (fabulous!) [Caddy web server](https://caddyserver.com), which has a sample file for Nextcloud at <https://github.com/caddyserver/examples/tree/master/nextcloud>. It's very security-minded and deliberately rejects TLS 1.0 as too old and insecure.

**Comment by Abraxos** [comment]
+1, I am using Caddy, and it works on my linux/windows devices, but not on my Mac for some reason.
