### ISSUE TITLE
Packaging of NextCloud client for Solus

### ISSUE THREAD

**Issue by sfalken-zz** [nextcloud/client_theming#36]
Hey there, I'm currently trying to package NextCloud for inclusion in the official Solus repos [http://www.solus-project.com](url)

Unfortunately, the client-theming tarballs don't actually contain any of the things neccessary for building on linux.    Per our packaging policy, we don't include items without actual release tarballs into the official repositories.  Grabbing the v2.2.4 tarball and doing a git pull for the linux stuff isn't allowed.    Can the linux items please get included in the release tarballs?

**Comment by Lochnair** [comment]
It certainly would be preferable if the client_theming tarballs included the client, but they don't really have to. The client_theming releases matches the versions used by the Owncloud client, so if you're using version 2.2.4 of the NextCloud theme, instead of downloading the submodule, download the 2.2.4 Owncloud client tarball and compile as usual (you'd need to change the path to the client folder though).

I'm using Solus myself, and plan to use NextCloud, so I threw together a package here: [nextcloud-client](https://github.com/Lochnair/solus-packages/tree/master/nextcloud-client). The extensions for Nautilus and Nemo will most likely conflict with the owncloud package, so I should probably make them conflict, but I can't see a good way to do that.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by enoch85** [comment]
Closing since it was over 2 weeks since anyone responded. Please reopen if this issue still persists. Thanks!
