### ISSUE TITLE
GUI optic

### ISSUE THREAD

**Issue by Kaelber** [nextcloud/client_theming#8]
I use the client as portable and the client look good. But I feel relating to the blue of nextcloud, the green colour is grazy (!). Its better to have a more fresh green or a green-yellow or in this way.

It´s only a idea.

**Comment by Kaelber** [comment]
or turquoise......

**Comment by LukasReschke** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
@Kaelber which colors exactly are you talking about? The blue is fine? But the green of the »all synced« icon is not good? How so?

The issue is that it has to be green because that’s the universal »all synced« icon color for the checkmark. We can’t make it blue since that’s the color of the »currently syncing« icon.

**Comment by Kaelber** [comment]
What I mean, is another kind of green, maybe a more blue green or yellow green, similar to

173,255,47
0,255,0
124,252,0

or so.....

**Comment by jancborchardt** [comment]
What’s the reasoning behind that? The greens you propose are almost neon green and would be very annoying because the green checkmark is shown most of the time.

The current green doesn’t push itself in the foreground because that’s not what it is for. It signifies that everything is ok.
