### ISSUE TITLE
segfault error results in client exit

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/client_theming#96]
I am using Nextcloud version 2.3.0beta1 on Arch Linux no updates pending. I did the upgrade from 2.2.4 and now the client starts without any errors and then shuts down after 1 or 2 minutes with this error.

`[  668.179943] nextcloud[4465]: segfault at 50c9850 ip 00007fe5c5830e1e sp 00007fff9f49aa88 error 4 in libc-2.24.so[7fe5c57ad000+195000]`

What can I do to mitigate this?

**Comment by chrismou** [comment]
Also seeing a segfault

`[40744.202514] nextcloud[20145]: segfault at 7fe3e7d16d60 ip 00007fe3e152f604 sp 00007fff5d2c1d80 error 7 in libQtGui.so.4.8.7[7fe3e137d000+aad000]`

Weirdly, when I bring it up in Gnome's search, it doesn't seem to pick up the icon anymore

![screenshot from 2017-03-09 23-59-22](https://cloud.githubusercontent.com/assets/319883/23776192/a7b33bd4-0524-11e7-9f26-699aa5dfbb92.png)

The logs show `failed to load stock icon nextcloud: Icon 'nextcloud' not present in theme (null)`

It was definitely working at one point, because I have my nextcloud folder looking like it did a week or so ago sat in my home folder. But sometime since then, it seems to have just stopped working.

Ubuntu 16.10  installed from the PPA

**Comment by iGormilhit** [comment]
Also encoutering a segmentation fault error resulting in crash of the client, with the archlinux AUR package. I've downgraded to 2.2.4-5.

**Comment by mightyBroccoli** [comment]
I went and did all pending upgrades to arch linux and now it works after 2 or 3 reboots. I didn´t change anything it just strted working after any of there restarts.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.
